
/*
* 输入数据*/
var mapInput = [
    [
        {province: '甘肃省', count: 57},
        {province: '山东省', count: 136},
        {province: '北京市', count: 3205},
        {province: '河北省', count: 227},
        {province: '浙江省', count: 49},
        {province: '江西省', count: 89},
        {province: '河南省', count: 117},
        {province: '山西省', count: 189},
        {province: '安徽省', count: 131},
        {province: '黑龙江省', count: 53},
        {province: '内蒙古自治区', count: 40},
        {province: '辽宁省', count: 59},
        {province: '云南省', count: 126},
        {province: '湖南省', count: 85},
        {province: '天津市', count: 43},
        {province: '四川省', count: 18},
        {province: '贵州省', count: 123},
        {province: '吉林省', count: 24},
        {province: '江苏省', count: 946},
        {province: '陕西省', count: 950},
        {province: '青海省', count: 438},
        {province: '新疆维吾尔自治区', count: 424},
        {province: '湖北省', count: 419},
        {province: '广东省', count: 396},
        {province: '重庆市', count: 365},
        {province: '香港', count: 180},
        {province: '澳门', count: 392},
        {province: '宁夏回族自治区', count: 243},
        {province: '广西壮族自治区', count: 170},
        {province: '福建省', count: 154},
        {province: '西藏自治区', count: 5},
        {province: '上海市', count: 10},
        {province: '海南省', count: 5},
        {province: '台湾省', count: 5}
    ],
    [
        {province: '甘肃省', count: 57},
        {province: '山东省', count: 136},
        {province: '北京市', count: 3205},
        {province: '河北省', count: 227},
        {province: '浙江省', count: 49},
        {province: '江西省', count: 89},
        {province: '河南省', count: 117},
        {province: '山西省', count: 189},
        {province: '安徽省', count: 131},
        {province: '黑龙江省', count: 53},
        {province: '内蒙古自治区', count: 40},
        {province: '辽宁省', count: 59},
        {province: '云南省', count: 126},
        {province: '湖南省', count: 85},
        {province: '天津市', count: 43},
        {province: '四川省', count: 18},
        {province: '贵州省', count: 89},
        {province: '吉林省', count: 117},
        {province: '江苏省', count: 189},
        {province: '陕西省', count: 131},
        {province: '青海省', count: 53},
        {province: '新疆维吾尔自治区', count: 40},
        {province: '湖北省', count: 59},
        {province: '广东省', count: 126},
        {province: '重庆市', count: 365},
        {province: '香港', count: 180},
        {province: '澳门', count: 392},
        {province: '宁夏回族自治区', count: 243},
        {province: '广西壮族自治区', count: 170},
        {province: '福建省', count: 154},
        {province: '西藏自治区', count: 5},
        {province: '上海市', count: 10},
        {province: '海南省', count: 5},
        {province: '台湾省', count: 5}
    ],
    [
        {province: '甘肃省', count: 57},
        {province: '山东省', count: 136},
        {province: '北京市', count: 3205},
        {province: '河北省', count: 227},
        {province: '浙江省', count: 49},
        {province: '江西省', count: 89},
        {province: '河南省', count: 117},
        {province: '山西省', count: 189},
        {province: '安徽省', count: 131},
        {province: '黑龙江省', count: 53},
        {province: '内蒙古自治区', count: 40},
        {province: '辽宁省', count: 59},
        {province: '云南省', count: 126},
        {province: '湖南省', count: 85},
        {province: '天津市', count: 43},
        {province: '四川省', count: 18},
        {province: '贵州省', count: 89},
        {province: '吉林省', count: 117},
        {province: '江苏省', count: 189},
        {province: '陕西省', count: 131},
        {province: '青海省', count: 53},
        {province: '新疆维吾尔自治区', count: 40},
        {province: '湖北省', count: 59},
        {province: '广东省', count: 126},
        {province: '重庆市', count: 85},
        {province: '香港', count: 43},
        {province: '澳门', count: 18},
        {province: '宁夏回族自治区', count: 89},
        {province: '广西壮族自治区', count: 170},
        {province: '福建省', count: 154},
        {province: '西藏自治区', count: 5},
        {province: '上海市', count: 10},
        {province: '海南省', count: 5},
        {province: '台湾省', count: 5}
    ],
    [
        {province: '甘肃省', count: 57},
        {province: '山东省', count: 136},
        {province: '北京市', count: 3205},
        {province: '河北省', count: 227},
        {province: '浙江省', count: 49},
        {province: '江西省', count: 89},
        {province: '河南省', count: 117},
        {province: '山西省', count: 189},
        {province: '安徽省', count: 131},
        {province: '黑龙江省', count: 53},
        {province: '内蒙古自治区', count: 40},
        {province: '辽宁省', count: 59},
        {province: '云南省', count: 126},
        {province: '湖南省', count: 85},
        {province: '天津市', count: 43},
        {province: '四川省', count: 18},
        {province: '贵州省', count: 89},
        {province: '吉林省', count: 49},
        {province: '江苏省', count: 89},
        {province: '陕西省', count: 117},
        {province: '青海省', count: 189},
        {province: '新疆维吾尔自治区', count: 131},
        {province: '湖北省', count: 53},
        {province: '广东省', count: 40},
        {province: '重庆市', count: 59},
        {province: '香港', count: 126},
        {province: '澳门', count: 85},
        {province: '宁夏回族自治区', count: 43},
        {province: '广西壮族自治区', count: 170},
        {province: '福建省', count: 154},
        {province: '西藏自治区', count: 5},
        {province: '上海市', count: 10},
        {province: '海南省', count: 5},
        {province: '台湾省', count: 5}
    ],
    [
        {province: '甘肃省', count: 57},
        {province: '山东省', count: 126},
        {province: '北京市', count: 85},
        {province: '河北省', count: 43},
        {province: '浙江省', count: 18},
        {province: '江西省', count: 89},
        {province: '河南省', count: 49},
        {province: '山西省', count: 189},
        {province: '安徽省', count: 131},
        {province: '黑龙江省', count: 53},
        {province: '内蒙古自治区', count: 40},
        {province: '辽宁省', count: 59},
        {province: '云南省', count: 126},
        {province: '湖南省', count: 85},
        {province: '天津市', count: 43},
        {province: '四川省', count: 18},
        {province: '贵州省', count: 89},
        {province: '吉林省', count: 49},
        {province: '江苏省', count: 89},
        {province: '陕西省', count: 117},
        {province: '青海省', count: 189},
        {province: '新疆维吾尔自治区', count: 131},
        {province: '湖北省', count: 53},
        {province: '广东省', count: 40},
        {province: '重庆市', count: 59},
        {province: '香港', count: 126},
        {province: '澳门', count: 85},
        {province: '宁夏回族自治区', count: 43},
        {province: '广西壮族自治区', count: 170},
        {province: '福建省', count: 154},
        {province: '西藏自治区', count: 5},
        {province: '上海市', count: 10},
        {province: '海南省', count: 5},
        {province: '台湾省', count: 5}
    ],
    [
        {province: '甘肃省', count: 57},
        {province: '山东省', count: 126},
        {province: '北京市', count: 85},
        {province: '河北省', count: 43},
        {province: '浙江省', count: 18},
        {province: '江西省', count: 89},
        {province: '河南省', count: 49},
        {province: '山西省', count: 40},
        {province: '安徽省', count: 59},
        {province: '黑龙江省', count: 126},
        {province: '内蒙古自治区', count: 85},
        {province: '辽宁省', count: 43},
        {province: '云南省', count: 18},
        {province: '湖南省', count: 89},
        {province: '天津市', count: 49},
        {province: '四川省', count: 89},
        {province: '贵州省', count: 117},
        {province: '吉林省', count: 189},
        {province: '江苏省', count: 131},
        {province: '陕西省', count: 117},
        {province: '青海省', count: 189},
        {province: '新疆维吾尔自治区', count: 131},
        {province: '湖北省', count: 53},
        {province: '广东省', count: 40},
        {province: '重庆市', count: 59},
        {province: '香港', count: 126},
        {province: '澳门', count: 85},
        {province: '宁夏回族自治区', count: 43},
        {province: '广西壮族自治区', count: 170},
        {province: '福建省', count: 154},
        {province: '西藏自治区', count: 5},
        {province: '上海市', count: 10},
        {province: '海南省', count: 5},
        {province: '台湾省', count: 5}
    ],
];
var mapElement = document.getElementById('map');
var center = [116.4551, 40.2539]; //北京的经纬度
renderMap(mapInput, mapElement,center);

/*
* 输入数据*/
var doubleBarInput = [
    [
        {name: '师范学院', maleCount: 160, femaleCount: 441},
        {name: '应用科技学院', maleCount: 441, femaleCount: 163},
        {name: '旅游学院', maleCount: 163, femaleCount: 121},
        {name: '应用文理学院', maleCount: 121, femaleCount: 160},
        {name: '艺术学院', maleCount: 160, femaleCount: 182},
        {name: '健康与环境学院', maleCount: 309, femaleCount: 309},
        {name: '机器人学院', maleCount: 129, femaleCount: 129},
        {name: '城市轨道交通与物流学院', maleCount: 51, femaleCount: 51},
        {name: '管理学院', maleCount: 182, femaleCount: 267},
        {name: '商务学院', maleCount: 309, femaleCount: 157},
        {name: '特殊教育学院', maleCount: 68, femaleCount: 102},
        {name: '智慧城市学院', maleCount: 110, femaleCount: 44}
    ],
    [
        {name: '师范学院', maleCount: 160, femaleCount: 441},
        {name: '应用科技学院', maleCount: 441, femaleCount: 163},
        {name: '旅游学院', maleCount: 163, femaleCount: 121},
        {name: '应用文理学院', maleCount: 121, femaleCount: 160},
        {name: '艺术学院', maleCount: 160, femaleCount: 182},
        {name: '健康与环境学院', maleCount: 182, femaleCount: 309},
        {name: '机器人学院', maleCount: 309, femaleCount: 129},
        {name: '城市轨道交通与物流学院', maleCount: 129, femaleCount: 51},
        {name: '管理学院', maleCount: 125, femaleCount: 267},
        {name: '商务学院', maleCount: 86, femaleCount: 157},
        {name: '特殊教育学院', maleCount: 68, femaleCount: 102},
        {name: '智慧城市学院', maleCount: 110, femaleCount: 44}
    ],
    [
        {name: '师范学院', maleCount: 160, femaleCount: 441},
        {name: '应用科技学院', maleCount: 441, femaleCount: 163},
        {name: '旅游学院', maleCount: 163, femaleCount: 121},
        {name: '应用文理学院', maleCount: 121, femaleCount: 160},
        {name: '艺术学院', maleCount: 160, femaleCount: 182},
        {name: '健康与环境学院', maleCount: 309, femaleCount: 309},
        {name: '机器人学院', maleCount: 129, femaleCount: 129},
        {name: '城市轨道交通与物流学院', maleCount: 51, femaleCount: 51},
        {name: '管理学院', maleCount: 163, femaleCount: 267},
        {name: '商务学院', maleCount: 160, femaleCount: 157},
        {name: '特殊教育学院', maleCount: 182, femaleCount: 102},
        {name: '智慧城市学院', maleCount: 309, femaleCount: 44}
    ],
    [
        {name: '师范学院', maleCount: 16, femaleCount: 441},
        {name: '应用科技学院', maleCount: 441, femaleCount: 163},
        {name: '旅游学院', maleCount: 163, femaleCount: 121},
        {name: '应用文理学院', maleCount: 121, femaleCount: 160},
        {name: '艺术学院', maleCount: 121, femaleCount: 441},
        {name: '健康与环境学院', maleCount: 160, femaleCount: 163},
        {name: '机器人学院', maleCount: 182, femaleCount: 121},
        {name: '城市轨道交通与物流学院', maleCount: 51, femaleCount: 121},
        {name: '管理学院', maleCount: 163, femaleCount: 160},
        {name: '商务学院', maleCount: 160, femaleCount: 157},
        {name: '特殊教育学院', maleCount: 182, femaleCount: 102},
        {name: '智慧城市学院', maleCount: 309, femaleCount: 44}
    ],
    [
        {name: '师范学院', maleCount: 16, femaleCount: 441},
        {name: '应用科技学院', maleCount: 441, femaleCount: 163},
        {name: '旅游学院', maleCount: 163, femaleCount: 121},
        {name: '应用文理学院', maleCount: 121, femaleCount: 160},
        {name: '艺术学院', maleCount: 121, femaleCount: 441},
        {name: '健康与环境学院', maleCount: 160, femaleCount: 163},
        {name: '机器人学院', maleCount: 182, femaleCount: 121},
        {name: '城市轨道交通与物流学院', maleCount: 51, femaleCount: 121},
        {name: '管理学院', maleCount: 163, femaleCount: 160},
        {name: '商务学院', maleCount: 160, femaleCount: 157},
        {name: '特殊教育学院', maleCount: 182, femaleCount: 102},
        {name: '智慧城市学院', maleCount: 309, femaleCount: 44}
    ],
    [
        {name: '师范学院', maleCount: 16, femaleCount: 441},
        {name: '应用科技学院', maleCount: 441, femaleCount: 163},
        {name: '旅游学院', maleCount: 163, femaleCount: 121},
        {name: '应用文理学院', maleCount: 121, femaleCount: 160},
        {name: '艺术学院', maleCount: 121, femaleCount: 441},
        {name: '健康与环境学院', maleCount: 160, femaleCount: 163},
        {name: '机器人学院', maleCount: 182, femaleCount: 121},
        {name: '城市轨道交通与物流学院', maleCount: 121, femaleCount: 121},
        {name: '管理学院', maleCount: 121, femaleCount: 160},
        {name: '商务学院', maleCount: 160, femaleCount: 157},
        {name: '特殊教育学院', maleCount: 157, femaleCount: 102},
        {name: '智慧城市学院', maleCount: 309, femaleCount: 44}
    ]
];
var  doubleBarElement= document.getElementById('doubleBar');
renderDoubleBar(doubleBarInput,doubleBarElement);
